version: "3"

services:
  server_manager:
    image: ghcr.io/cartesi/rollups-host-runner:main
    ports:
      - "5004:5004"
    environment:
      - RUST_LOG=warn

  advance_runner:
    environment:
      - SNAPSHOT_ENABLED=false
